project:
  type: book
  output-dir: _book

book:
  title: "Digital Design Lab"
  author: "Ratko Pilipović"
  date: today
  chapters:
    - index.qmd
    - part: "Lab Exercises"
      chapters:
        - chapters/01-tools-intro.qmd
        - chapters/02-alu.qmd
        - chapters/03-sequential.qmd
        - chapters/04-structural-modeling.qmd
      #  - chapters/05-counter-sevenseg.qmd
      #  - chapters/06-uart.qmd
      #  - chapters/07-mcs.qmd
      #  - chapters/08-fpro-7seg.qmd
      #  - chapters/09-soc-verification.qmd

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrbook
    pdf-engine: tectonic
